WIP: Sywa 20
ScrabbleYourWordsApp/word-dump-service pull request #4
Opened 2020-04-14 15:26 UTC by AnthonyHeremans

2020-04-14 15:49 UTC, BenjaminDendas requested changes
Minor changes die gedaan moeten worden, voor de rest ziet het er ok uit.

2020-04-14 15:49 UTC, BenjaminDendas commented on logger/Logger.js
> +const logDir = 'log';
Deze folder wil je doorgeven vanuit de environment file omdat je die eigenlijk wilt aanpasbaar maken zonder dat je opnieuw je code zou moeten deployen.

2020-04-14 15:49 UTC, BenjaminDendas commented on logger/Logger.js
> +  filename: `${logDir}/%DATE%-results.log`,
De -results mag gerenamed worden naar iets meer globaal voor de service. bijvoorbeeld: `word-dump-service-%date%.log` of gewoon `%date%.log`

2020-04-14 15:49 UTC, BenjaminDendas commented on logger/Logger.js
> +  datePattern: 'YYYY-MM-DD',
Ik zou hier hetzelfde formaat aanhouden zoals je doet in de console, namelijk: `YYYY-MM-DD HH:mm:ss`

2020-04-14 15:49 UTC, BenjaminDendas commented on processedFiles/tetsst - Copy (2).txt
> +khjk
Deze files zou ik verwijderen uit de git en de eigenlijke corpus file gebruiken

2020-04-14 15:49 UTC, BenjaminDendas commented on processedFiles/tetsst - Copy (3).txt
> +khjk
Deze files zou ik verwijderen uit de git en de eigenlijke corpus file gebruiken

2020-04-14 15:49 UTC, BenjaminDendas commented on processedFiles/tetsst - Copy (4).txt
> +khjk
Deze files zou ik verwijderen uit de git en de eigenlijke corpus file gebruiken

2020-04-14 15:49 UTC, BenjaminDendas commented on processedFiles/tetsst - Copy (5).txt
> +khjk
Deze files zou ik verwijderen uit de git en de eigenlijke corpus file gebruiken

2020-04-14 15:49 UTC, BenjaminDendas commented on processedFiles/tetsst - Copy (6).txt
> +khjk
Deze files zou ik verwijderen uit de git en de eigenlijke corpus file gebruiken

2020-04-14 15:49 UTC, BenjaminDendas commented on processedFiles/tetsst - Copy (7).txt
> +khjk
Deze files zou ik verwijderen uit de git en de eigenlijke corpus file gebruiken

2020-04-14 15:49 UTC, BenjaminDendas commented on processedFiles/tetsst - Copy.txt
> +khjk
Deze files zou ik verwijderen uit de git en de eigenlijke corpus file gebruiken

2020-04-14 15:49 UTC, BenjaminDendas commented on processedFiles/tetsst.txt
> +khjk
Deze files zou ik verwijderen uit de git en de eigenlijke corpus file gebruiken

2020-04-14 15:49 UTC, BenjaminDendas commented on wordReader/WordReader.js
> +      glob(directory.concat('/*.txt'), (err, files) => {
Dit wil je configureerbaar maken vanuit de environmentfile zodat je niet gebonden bent aan .txt bestanden. Indien we later bv een excel willen verwerken dan kan het zijn dat we deze code kunnen hergebruiken.

2020-04-14 17:43 UTC, AnthonyHeremans commented on logger/Logger.js
> +  datePattern: 'YYYY-MM-DD',
Dit is neit het formaat waarin het word weg geschreven maar het formaat hoe de textfile genoemt wordt. Hier is de tijd niet relevant. Wordt dus genegeerd.

2020-04-14 18:16 UTC, BenjaminDendas commented on logger/Logger.js
> +  datePattern: 'YYYY-MM-DD',
Ok

2020-04-15 19:10 UTC, BenjaminDendas requested changes
Enkel de .env file nog commiten en dan is het in orde

2020-04-15 19:18 UTC, merged